'use strict';

// taking the dom elememts in a variable, SELECTING ELEMENTS
const palyer0El = document.querySelector('.player--0');
const palyer1El = document.querySelector('.player--1');

const score0EL = document.querySelector('#score--0');
const score1EL = document.getElementById('score--1');

const current0El = document.getElementById('current--0');
const current1El = document.getElementById('current--1');

const diceEle = document.querySelector('.dice');

const btnNew = document.querySelector('.btn--new');
const btnHold = document.querySelector('.btn--hold');
const btnRoll = document.querySelector('.btn--roll');

let score, currentScore, activePlayer, playing;

const init = function () {
  // starting conditions
  score = [0, 0];
  currentScore = 0;
  activePlayer = 0;
  playing = true; // boolean value to where at this condition only the game can be played

  score0EL.textContent = 0;
  score1EL.textContent = 0;
  current0El.textContent = 0;
  current1El.textContent = 0;

  // remvoing the winner class
  diceEle.classList.add('hidden'); // hidden class added to remove the dice.png image
  palyer0El.classList.remove('player--winner');
  palyer1El.classList.remove('player--winner');
  palyer0El.classList.add('player--active');
  palyer1El.classList.remove('player--active');
};

init(); // calling the above function to run when the page reloaded and during the start of the game

// function to switch the player
const switchPlayer = function () {
  document.getElementById(`current--${activePlayer}`).textContent = 0;
  currentScore = 0;
  activePlayer = activePlayer === 0 ? 1 : 0;

  // this changes the back-gound of active player to white toggle function is used
  palyer0El.classList.toggle('player--active');
  palyer1El.classList.toggle('player--active');
};

// rolling dice functionallity
btnRoll.addEventListener('click', function () {
  if (playing) {
    // if playin then only this if excutes
    // 1. generating a random dice number
    const dice = Math.trunc(Math.random() * 6) + 1;

    // display the dice
    diceEle.classList.remove('hidden'); // added the dice.png image based on the dice roll generated by random number
    diceEle.src = `dice-${dice}.png`;

    // 3.check for the rolled 1
    if (dice !== 1) {
      currentScore += dice; // if the roll != 1 then it is added to current score to maintain the score of the player
      document.getElementById(`current--${activePlayer}`).textContent =
        currentScore; // dom manipulation in web page
    }

    // switch the player
    else {
      switchPlayer(); // here its a condition of dice number == 1 so the player is changed
    }
  }
});

btnHold.addEventListener('click', function () {
  if (playing) {
    // 1. update the player 1 score
    score[activePlayer] += currentScore;
    document.getElementById(`score--${activePlayer}`).textContent =
      score[activePlayer];

    //2. check if the score >= 100
    if (score[activePlayer] >= 20) {
      // finish the game
      playing = false; //setting up the playig to false to stop working of buttons
      diceEle.classList.add('hidden');
      document
        .querySelector(`.player--${activePlayer}`)
        .classList.add('player--winner');
      document
        .querySelector(`.player--${activePlayer}`)
        .classList.remove('player--active');
    } else {
      // 3.switch the player
      switchPlayer(); // function call to switch the player
    }
  }
});

// event listener function on newgame button to reset all the value to initial value
btnNew.addEventListener('click', init);
